---
title: "R Notebook"
output: html_notebook
---

```{r setup}
require(ggplot2)
require(ggpubr)
require(dplyr)
require(reshape2)

colors <- c("yellowgreen", "violetred4")
cOn <- colors[1]
cOff <- colors[2]

#model_entropy_replicas <- read.csv("model_entropy_simple.csv")
#model_entropy_replicas <- melt(model_entropy_replicas, id.vars="n", measure.vars=c("pvn", "un"))

prob_cmp <- read.csv("problem_cmp.csv")
colnames(prob_cmp) <- c("tr", "não", "sim")
prob_cmp$tr <- prob_cmp$tr/1000 # conv. to ms.
prob_cmp <- melt(prob_cmp, id.vars="tr", measure.vars=c("sim", "não"))
```

```{r}
med_sim <- prob_cmp %>% filter(variable=="sim" & value>0.5) %>% head(n=1)
med_nao <- prob_cmp %>% filter(variable=="não" & value>0.5) %>% head(n=1)
perc_sim <- prob_cmp %>% filter(value>=0.9990 & variable=="sim") %>% head(n=1)
perc_nao <- prob_cmp %>% filter(value>=0.9990 & variable=="não") %>% head(n=1)

(perc_sim$tr/med_sim$tr)/(perc_nao$tr/med_nao$tr)

(perc_sim$tr-med_sim$tr)/(perc_nao$tr-med_nao$tr)

ggplot(prob_cmp, aes(x=tr, y=value, group=variable)) +
  geom_line(aes(color=variable, linetype=variable), size=1.2) +
  geom_vline(xintercept=perc_sim$tr, linetype=1, size=0.9, color=cOn, alpha=0.4) +
  geom_vline(xintercept=perc_nao$tr, linetype=2, size=0.9, color=cOff, alpha=0.4) +
  geom_vline(xintercept=med_sim$tr, linetype=1, size=0.9, color=cOn, alpha=0.4) +
  geom_vline(xintercept=med_nao$tr, linetype=2, size=0.9, color=cOff, alpha=0.4) +
  annotate(geom="text", x=med_sim$tr-0.4, y=0.9945, label="Medianas", angle = 90, size=4, alpha=0.7, color="darkgray", fontface="bold") +
  annotate(geom="text", x=perc_nao$tr+((perc_sim$tr-perc_nao$tr)/2), y=0.9905, label="Distância entre os 99.9 percentis", size=4, alpha=0.7, color="darkgray", fontface="bold") +
  geom_segment(aes(x=perc_nao$tr, y=0.991, xend=perc_sim$tr, yend=0.991), arrow = arrow(length = unit(0.3, "cm"),  ends = "both", type = "closed"), size=0.1, colour="darkgray", show.legend = FALSE) +
  coord_cartesian(ylim = c(0.99, 1)) +
  scale_x_continuous(breaks=seq(0,20, by=2)) +
  scale_color_manual(values=colors) +
  guides(linetype=FALSE) +
  labs(
    x="Tempo de Resposta (ms)",
    y="Função de Distribuição Cumulativa",
    color="Utilização do CTC")+ 
  theme_pubr() +
  theme(
    legend.position="bottom",
    panel.grid.major.x = element_line(colour = "darkgray", linetype = 3))

ggsave("res_model_replicas_tr.png")
```

```{r res_model_replicas_pvn}
ggplot(read.csv("model_entropy_simple_5_replicas.csv"), aes(x=nReplicas, y=pvn)) +
  #geom_line(size=0.8, color=cOn) +
  #geom_point(size=2, color=cOn) +
  geom_bar(stat="identity", fill=cOn) +
  scale_x_discrete(limits=1:10) +
  scale_y_continuous(limit=0:1,breaks = seq(0,1,0.1), labels = function(x) paste0(x*100, "%")) +
  scale_color_manual(values=colors) +
  labs(x="Número de Réplicas", y="Perda de Vazão Normalizada") +
  theme_pubr() +
  theme(
    legend.position="bottom",
    panel.grid.major.x = element_line(colour = "darkgray", linetype = 3),
    panel.grid.major.y = element_line(colour = "darkgray", linetype = 3))
ggsave("res_model_replicas_pvn.png")
```

```{r res_model_replicas_pcp}
ggplot(read.csv("model_entropy_simple_5_replicas.csv"), aes(x=nReplicas, y=pcp)) +
  #geom_line(size=0.8, color=cOn) +
  #geom_point(size=2, color=cOn) +
  geom_bar(stat="identity", fill=cOn) +
  scale_x_discrete(limits=1:10) +
  scale_y_continuous(limit=0:1,breaks = seq(0,1,0.1), labels = function(x) paste0(x*100, "%")) +
  scale_color_manual(values=colors) +
  labs(x="Número de Réplicas", y="Perda de Capacidade de Processamento") +
  theme_pubr() +
  theme(
    legend.position="bottom",
    panel.grid.major.x = element_line(colour = "darkgray", linetype = 3),
    panel.grid.major.y = element_line(colour = "darkgray", linetype = 3))
ggsave("res_model_replicas_pcp.png")
```

```{r res_model_replicas_markov}
ggplot(read.csv("model_entropy_simple_5_replicas.csv"), aes(x=nReplicas, y=nMarkings)) +
  geom_bar(stat="identity", fill=cOn) +
  scale_x_discrete(limits=1:5) +
  scale_color_manual(values=colors) +
  labs(x="Número de Réplicas", y="Número de Marcações") +
  theme_pubr() +
  theme(
    legend.position="bottom",
    panel.grid.major.x = element_line(colour = "darkgray", linetype = 3),
    panel.grid.major.y = element_line(colour = "darkgray", linetype = 3))
ggsave("res_model_replicas_markings.png")
```